### ISSUE TITLE
Swift 2.2 support.

### ISSUE THREAD

**Issue by adamszeptycki** [SwiftKit/Cuckoo#6] opened 2016-03-22 10:46 UTC
Sadly it's not working with Swift 2.3.
There is one error in this line:
`XCTFail(description.description, file: sourceLocation.file, line: sourceLocation.line)`
changing it to this:
`XCTFail(description.description, file: "sourceLocation.file", line: sourceLocation.line)`
made it work (I know it's not proper solution).
But then I had a bunch of error that labels are not allowed in closures (Xcode can auto fix that).
But at the end all tests are failing with fatal error. "No stuff for method was provided." (Tests were passing before the update).

Any plans to solving that?

**Comment by TadeasKriz** [comment] 2016-03-22 10:51
Hey, thanks for reporting this, I just installed Xcode 7.3 so I can try it out and fix it.

**Comment by adamszeptycki** [comment] 2016-03-22 10:52
Looking forward for the fix :D

**Comment by TadeasKriz** [comment] 2016-03-22 12:01
It seems that Swift 2.3 broken some thing that were necessary for mocking @noescape closure parameters. I'm trying to find out a workaround, but with no luck. I'll keep you posted.

**Comment by TadeasKriz** [comment] 2016-03-22 13:15
Well, we might be out of luck until the next Swift version is released. I'm not able to come up with a workaround to this change. This rules out both `@autoclosure` and `@noescape`. I will probably change it so that you can test whether it was called and the Spy will still work properly, but the following will not be supported:

```
when(something.methodWithNoescape).then { noescapeClosure in
    noescapeClosure()
}
```

This will crash because the closure will be just a stub.

**Comment by TadeasKriz** [comment] 2016-03-22 13:26
> Declaration `let x: (String, String -> Void) -> Void`
vs
> Declaration `let x: (String, @noescape String -> Void) -> Void`

The first one can be called directly with the parameters like so: `x("something", { _ in })`, however the second one cannot. The second one requires parameters to be wrapped in a tuple like so: `x(("something", { _ in }))`, but then the compiler complains that making a tuple with `@noescape` closure might enable the closure to escape. So this is a dead end :/

**Comment by TadeasKriz** [comment] 2016-03-29 10:40
Sorry for the delay, I have a lot to do and so little time these days. Currently I am not able to get CuckooGenerator to compile with XCode 7.3. It complains that some of the dependencies are built with older Swift, but I did run `carthage build` and then `Clean + Build` in Xcode, but still no luck.

**Comment by TadeasKriz** [comment] 2016-05-03 09:43
@adamszeptycki Could you try it with Swift 2.2 please? :) @cmandlbaur fixed the generator to work with Swift 2.2 :)

**Comment by adamszeptycki** [comment] 2016-05-04 14:17
@TadeasKriz Hey thanks a lot.  Sadly I had to remove everything Cuckoo related from previous project. But next month I will have some time to test out new library ;)
Again thanks a lot :)

**Comment by TadeasKriz** [comment] 2016-06-15 07:27
Should be fixed in Cuckoo 0.5.0.

**Closed** 2016-06-15 07:27 UTC
Labels: bug

**Comment by krin-san** [comment] 2016-08-23 08:02
Hello, @TadeasKriz, I experienced another issue with my Swift 2.2 based project.
This is my source class and Cockoo auto-generated class:
```swift
class MyClass {
    func objects(byFilter filter: String) -> String {
        return ""
    }
}
```
```swift
class MockMyClass: MyClass, Cuckoo.Mock {
    let manager: Cuckoo.MockManager<__StubbingProxy_MyClass, __VerificationProxy_MyClass> = Cuckoo.MockManager()

    private var observed: MyClass?

    required override init() {
    }

    required init(spyOn victim: MyClass) {
        observed = victim
    }
    
    override func objects(byFilter filter: String)-> String {
        return manager.call("objects(byFilter:String)-> String", parameters: (filter), original: observed.map { o in return { (byFilter filter: String)-> String in o.objects(byFilter: filter) } })
    }

    struct __StubbingProxy_MyClass: Cuckoo.StubbingProxy {
        // ...
    }

    struct __VerificationProxy_MyClass: Cuckoo.VerificationProxy {
        // ...
    }
}
```
The compiler complains on the `(byFilter filter: String)` part of the overrided `objects()` method with the following error message: **Closure cannot have keyword arguments**, and suggest to remove a `byFilter` keyword.

The problem is the class is auto-generated and after each build developer should manually remove these external names for the first method parameter. I have a lot of functions in my real project like `benefits(forCategory category: BenefitCategory)` and `categories(inCity city: City)`.

Is there any workaround in code generator to remove parameter's external name from the closure?

**Comment by TadeasKriz** [comment] 2016-08-23 08:06
Doh! Silly bug in the generator. @FilipDolnik could you look at it and fix it?

@krin-san We plan releasing larger patch that should fix a lot of things very soon, I'll keep you posted.

**Comment by krin-san** [comment] 2016-08-23 08:11
Thanks for the quick reply! I'll be waiting for the next Cockoo release.
